---
- name: Install NVIDIA Container Toolkit on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Download NVIDIA GPG key
      ansible.builtin.shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add NVIDIA container repo
      ansible.builtin.shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Add NVIDIA container repo
      ansible.builtin.shell: |
        export NVIDIA_CONTAINER_TOOLKIT_VERSION=1.17.8-1 && \
        sudo apt-get install -y \
        nvidia-container-toolkit=${NVIDIA_CONTAINER_TOOLKIT_VERSION} \
        nvidia-container-toolkit-base=${NVIDIA_CONTAINER_TOOLKIT_VERSION} \
        libnvidia-container-tools=${NVIDIA_CONTAINER_TOOLKIT_VERSION} \
        libnvidia-container1=${NVIDIA_CONTAINER_TOOLKIT_VERSION}
      #args:
        #creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    #- name: Install NVIDIA Container Toolkit
      #ansible.builtin.apt:
        #name: nvidia-container-toolkit
        #state: present
